# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a74d32920a136e76f1ba183994195205fbf821fec596dccfa62f7d1688a90e2b1804008ab56ae96542eddfeccb1723877f6a26efe93f91e9bad4624de253150

test:
  secret_key_base: 48a56ef3b05b508de5bd6b7e6d04273aa8279aeffb2853c44b5b78ca22367e65bd93d03cc169dfc64f189dbe54edea7d4fffac365b447ac8cd77e48dba886f83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
